# Generated by Django 4.2.26 on 2025-11-23 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Açıklama / Ad')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tutar (TL)')),
                ('transaction_type', models.CharField(choices=[('expense', 'Harcama'), ('income', 'Gelen Para')], default='expense', max_length=10)),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Tarih')),
                ('installment_count', models.IntegerField(default=0, verbose_name='Taksit Sayısı (Peşinse 0)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
