# Generated by Django 4.2.26 on 2025-11-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_recurring',
            field=models.BooleanField(default=False, verbose_name='Her Ay Tekrarla'),
        ),
    ]
