# Generated by Django 4.2.26 on 2025-12-21 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_transaction_is_recurring'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, verbose_name='Ürün Linki')),
                ('product_name', models.CharField(max_length=255, verbose_name='Ürün Adı')),
                ('site_name', models.CharField(max_length=50, verbose_name='Site (Amazon/Hepsiburada vs.)')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Güncel Fiyat')),
                ('seller_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Satıcı')),
                ('last_checked', models.DateTimeField(auto_now=True, verbose_name='Son Kontrol')),
                ('custom_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sizin Verdiğiniz İsim')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
