# Generated by Django 4.2.26 on 2025-12-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_trackedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedproduct',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Orijinal Fiyat'),
        ),
    ]
