# Generated by Django 4.2.26 on 2025-12-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_trackedproduct_original_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedproduct',
            name='last_status',
            field=models.CharField(choices=[('stable', 'Aynı Fiyat'), ('dropped', 'Fiyat Düştü'), ('increased', 'Fiyat Yükseldi')], default='stable', max_length=20, verbose_name='Son Durum'),
        ),
        migrations.AddField(
            model_name='trackedproduct',
            name='notification_email',
            field=models.EmailField(default='', max_length=254, verbose_name='Bildirim Maili'),
        ),
        migrations.AlterField(
            model_name='trackedproduct',
            name='site_name',
            field=models.CharField(max_length=50, verbose_name='Site'),
        ),
    ]
