# Generated by Django 4.2.26 on 2025-12-21 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_trackedproduct_last_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedproduct',
            name='previous_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Önceki Fiyat'),
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.trackedproduct')),
            ],
        ),
    ]
