# Generated by Django 4.2.26 on 2025-12-22 00:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_trackedproduct_previous_price_pricehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
