# Generated by Django 4.2.26 on 2025-12-22 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_pricehistory_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricehistory',
            old_name='date',
            new_name='date2',
        ),
    ]
