# Generated by Django 4.2.26 on 2025-12-22 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_date_pricehistory_date2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricehistory',
            old_name='date2',
            new_name='date',
        ),
    ]
