# Generated by Django 4.2.26 on 2025-12-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_date2_pricehistory_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedproduct',
            name='variant_size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Boyut/Varyant'),
        ),
        migrations.AddField(
            model_name='trackedproduct',
            name='variant_sku',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Varyant SKU'),
        ),
    ]
