# Generated by Django 4.2.26 on 2025-12-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_trackedproduct_variant_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedproduct',
            name='plus_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Plus Fiyatı'),
        ),
    ]
