# Generated by Django 4.2.26 on 2025-12-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedproduct',
            name='is_in_stock',
            field=models.BooleanField(default=True, verbose_name='Stokta Var'),
        ),
    ]
