# Generated by Django 4.2.26 on 2025-12-24 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_trackedproduct_is_in_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Yeni Not', max_length=200, verbose_name='Başlık')),
                ('content', models.TextField(blank=True, verbose_name='İçerik')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Sabitlenmiş')),
                ('color', models.CharField(default='#ffffff', max_length=20, verbose_name='Renk')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Not',
                'verbose_name_plural': 'Notlar',
                'ordering': ['-is_pinned', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('start_date', models.DateField(verbose_name='Başlangıç')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Bitiş')),
                ('event_type', models.CharField(choices=[('event', 'Etkinlik'), ('reminder', 'Hatırlatıcı'), ('birthday', 'Doğum Günü'), ('special', 'Özel An')], default='event', max_length=20, verbose_name='Tür')),
                ('color', models.CharField(default='#667eea', max_length=20, verbose_name='Renk')),
                ('all_day', models.BooleanField(default=True, verbose_name='Tüm Gün')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Takvim Etkinliği',
                'verbose_name_plural': 'Takvim Etkinlikleri',
                'ordering': ['start_date'],
            },
        ),
    ]
