# Generated by Django 4.2.26 on 2025-12-24 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_note_calendarevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='is_recurring',
            field=models.BooleanField(default=False, verbose_name='Her Yıl Tekrarla'),
        ),
    ]
