# Generated by Django 4.2.26 on 2025-12-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_calendarevent_is_recurring'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('general', 'Genel'), ('food', 'Yemek & Restoran'), ('transport', 'Ulaşım'), ('market', 'Market & Alışveriş'), ('bills', 'Fatura & Abonelik'), ('entertainment', 'Eğlence'), ('clothing', 'Giyim'), ('health', 'Sağlık'), ('education', 'Eğitim'), ('rent', 'Kira'), ('salary', 'Maaş'), ('bonus', 'Prim & Bonus'), ('other', 'Diğer')], default='general', max_length=20, verbose_name='Kategori'),
        ),
    ]
