# Generated by Django 4.2.26 on 2025-12-28 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0016_transaction_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionWheel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Çark Adı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_template', models.BooleanField(default=False, verbose_name='Şablon mu?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Karar Çarkı',
                'verbose_name_plural': 'Karar Çarkları',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WheelOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='Seçenek')),
                ('color', models.CharField(default='#667eea', max_length=20, verbose_name='Renk')),
                ('order', models.PositiveIntegerField(default=0)),
                ('wheel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.decisionwheel')),
            ],
            options={
                'verbose_name': 'Çark Seçeneği',
                'verbose_name_plural': 'Çark Seçenekleri',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DecisionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wheel_name', models.CharField(max_length=100, verbose_name='Çark Adı')),
                ('result', models.CharField(max_length=100, verbose_name='Sonuç')),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Karar Geçmişi',
                'verbose_name_plural': 'Karar Geçmişleri',
                'ordering': ['-decided_at'],
            },
        ),
    ]
