# Generated by Django 4.2.26 on 2026-01-03 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0017_decisionwheel_wheeloption_decisionhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Mekan Adı')),
                ('category', models.CharField(choices=[('restaurant', 'Restoran'), ('cafe', 'Kafe'), ('bar', 'Bar/Pub'), ('fastfood', 'Fast Food'), ('bakery', 'Fırın/Pastane'), ('dessert', 'Tatlı/Dondurma'), ('other', 'Diğer')], max_length=20, verbose_name='Kategori')),
                ('cuisine_type', models.CharField(blank=True, max_length=100, verbose_name='Mutfak Türü')),
                ('address', models.TextField(blank=True, verbose_name='Adres')),
                ('city', models.CharField(default='İstanbul', max_length=100, verbose_name='Şehir')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='İlçe')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Enlem')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Boylam')),
                ('price_range', models.IntegerField(choices=[(1, '₺ (Ekonomik)'), (2, '₺₺ (Orta)'), (3, '₺₺₺ (Pahalı)'), (4, '₺₺₺₺ (Lüks)')], default=2, verbose_name='Fiyat Aralığı')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('website', models.URLField(blank=True, max_length=300, verbose_name='Website')),
                ('times_visited', models.IntegerField(default=0, verbose_name='Ziyaret Sayısı')),
                ('average_rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Ortalama Puan')),
                ('average_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Ortalama Harcama')),
                ('google_place_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Google Place ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mekan',
                'verbose_name_plural': 'Mekanlar',
                'ordering': ['-average_rating', '-times_visited'],
            },
        ),
        migrations.CreateModel(
            name='WatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Başlık')),
                ('item_type', models.CharField(choices=[('movie', 'Film'), ('series', 'Dizi'), ('book', 'Kitap'), ('podcast', 'Podcast'), ('documentary', 'Belgesel')], max_length=20, verbose_name='Tür')),
                ('status', models.CharField(choices=[('planning', 'İzleyeceğim/Okuyacağım'), ('ongoing', 'İzliyorum/Okuyorum'), ('completed', 'Tamamlandı'), ('dropped', 'Bıraktım'), ('paused', 'Duraklattım')], default='planning', max_length=20, verbose_name='Durum')),
                ('genre', models.CharField(blank=True, max_length=100, verbose_name='Kategori')),
                ('creator', models.CharField(blank=True, max_length=200, verbose_name='Yönetmen/Yazar')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Yıl')),
                ('poster_url', models.URLField(blank=True, max_length=500, verbose_name='Poster URL')),
                ('total_episodes', models.IntegerField(blank=True, null=True, verbose_name='Toplam Bölüm')),
                ('current_episode', models.IntegerField(default=0, verbose_name='Güncel Bölüm')),
                ('total_pages', models.IntegerField(blank=True, null=True, verbose_name='Toplam Sayfa')),
                ('current_page', models.IntegerField(default=0, verbose_name='Güncel Sayfa')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Puan')),
                ('review', models.TextField(blank=True, verbose_name='İnceleme')),
                ('favorite_quotes', models.TextField(blank=True, verbose_name='Favori Alıntılar')),
                ('is_shared', models.BooleanField(default=False, verbose_name='Ortak İzleniyor')),
                ('started_at', models.DateField(blank=True, null=True, verbose_name='Başlangıç Tarihi')),
                ('completed_at', models.DateField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'İzlenen/Okunan',
                'verbose_name_plural': 'İzlenenler/Okunanlar',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaceVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(default=django.utils.timezone.now, verbose_name='Ziyaret Tarihi')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Puan')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Harcama (₺)')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('what_we_ate', models.TextField(blank=True, verbose_name='Ne Yedik')),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='place_photos/', verbose_name='Fotoğraf 1')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='place_photos/', verbose_name='Fotoğraf 2')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='place_photos/', verbose_name='Fotoğraf 3')),
                ('would_return', models.BooleanField(default=True, verbose_name='Tekrar Gider miyiz?')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Favori')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='core.place', verbose_name='Mekan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Mekan Ziyareti',
                'verbose_name_plural': 'Mekan Ziyaretleri',
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='PlaceRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_place_data', models.TextField(verbose_name='Öneri Verisi')),
                ('similarity_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Benzerlik Skoru')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='core.place', verbose_name='Kaynak Mekan')),
            ],
            options={
                'verbose_name': 'Mekan Önerisi',
                'verbose_name_plural': 'Mekan Önerileri',
                'ordering': ['-similarity_score'],
            },
        ),
    ]
