# Generated by Django 4.2.26 on 2026-01-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_place_watchitem_placevisit_placerecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='photo_photographer',
            field=models.CharField(blank=True, max_length=200, verbose_name='Fotoğrafçı'),
        ),
        migrations.AddField(
            model_name='place',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Fotoğraf URL'),
        ),
        migrations.AddField(
            model_name='place',
            name='unsplash_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Unsplash ID'),
        ),
        migrations.AddField(
            model_name='watchitem',
            name='backdrop_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Backdrop URL'),
        ),
        migrations.AddField(
            model_name='watchitem',
            name='overview',
            field=models.TextField(blank=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='watchitem',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='TMDB ID'),
        ),
    ]
