# Generated by Django 4.2.26 on 2026-01-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_place_photo_photographer_place_photo_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricehistory',
            options={'ordering': ['-date']},
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['product', '-date'], name='core_priceh_product_3ac34a_idx'),
        ),
    ]
