# Generated by Django 4.2.26 on 2026-01-16 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_pricehistory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
        migrations.DeleteModel(
            name='CalendarEvent',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
