# Generated by Django 4.2.26 on 2026-01-28 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_note_user_delete_calendarevent_delete_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decisionwheel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='place',
            name='user',
        ),
        migrations.RemoveField(
            model_name='placerecommendation',
            name='source_place',
        ),
        migrations.RemoveField(
            model_name='placevisit',
            name='place',
        ),
        migrations.RemoveField(
            model_name='placevisit',
            name='user',
        ),
        migrations.RemoveField(
            model_name='watchitem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wheeloption',
            name='wheel',
        ),
        migrations.DeleteModel(
            name='DecisionHistory',
        ),
        migrations.DeleteModel(
            name='DecisionWheel',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.DeleteModel(
            name='PlaceRecommendation',
        ),
        migrations.DeleteModel(
            name='PlaceVisit',
        ),
        migrations.DeleteModel(
            name='WatchItem',
        ),
        migrations.DeleteModel(
            name='WheelOption',
        ),
    ]
